### ISSUE TITLE
Iteración 3 - Implementación

### ISSUE THREAD

**Issue by trykilla** [trykilla/ISO2-2023-BC03#28]

**Comment by pedroocampos** [comment]
Implementación_Servidor_It3 terminada https://github.com/trykilla/ISO2-2023-BC03/commit/c28c63e96b268ab1651392a19a156408ce6f8416

Implementación_Dueño_It3 terminada https://github.com/trykilla/ISO2-2023-BC03/commit/c9d79ba244a406df7459fa9c0ab1f1206e43141b

**Comment by trykilla** [comment]
Perfecto, gracias.
